
ACCOUNTS=[
"GAASD6MEPCGI6J7HUZR7PKYN3V54P7ODIHDNRNCDQURCRDBTZ5AQYIJP",
"GBBCZFSYPTQPCYP7ZAHR3JTATOND5CGS7ENRAGGQSVN33UOQN42EFQQO",
"GBIBV7VU4KNE6PQS5M3JG5VGOREL7JXILTTWWYIXC62GKUSXLY4IGGKE",
"GBTUEWD3WT2IEFDQKPEG6WOAOCJO433IQ3NGHOD6E234QNAD3ZOQ3A7Z"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Free Weed Calculator"
ORG_DBA=""
ORG_URL="http://freeweedcalculator.com/TOKE"
ORG_LOGO="http://freeweedcalculator.com/TOKELOGO.PNG"
ORG_DESCRIPTION="Free Weed Calculator is a web host of a free calculator. It engages in other related technologies as well."
ORG_PHYSICAL_ADDRESS="Chicago IL"
ORG_PHYSICAL_ADDRESS_ATTESTATION=""
ORG_PHONE_NUMBER="1 (234) 562-2133"
ORG_PHONE_NUMBER_ATTESTATION=""
ORG_KEYBASE="davewinnyk"
ORG_TWITTER="fakedavewinnyk"
ORG_GITHUB="davewinnyk"
ORG_OFFICIAL_EMAIL="davewinnyk@gmail.com"

[[PRINCIPALS]]
name="David Bryan Winnyk"
email="davewinnyk@gmail.com"
keybase="davewinnyk"
twitter="fakedavewinnyk"
github="davewinnyk"
id_photo_hash=""
verification_photo_hash=""


# asset with meta info
[[CURRENCIES]]
code="TOKE"
issuer="GAASD6MEPCGI6J7HUZR7PKYN3V54P7ODIHDNRNCDQURCRDBTZ5AQYIJP"
is_asset_anchored=false
asset_anchor=""
display_decimals=2
name="The Toke Token"
desc="TOKE is a crypto for cannabis. Show your love for your buds by sending them a TOKE."
redemption_instructions="Trade your TOKE with the buds you love. TOKE should only be used to trade off-network assets acquired within accordance with Federal, State, and Local Laws." 
conditions="By trading in TOKE you agree to our conditions and redemption_instructions."
image="http://freeweedcalculator.com/TOKELOGO.PNG"


