
ACCOUNTS=[
"GAASD6MEPCGI6J7HUZR7PKYN3V54P7ODIHDNRNCDQURCRDBTZ5AQYIJP",
"GBBCZFSYPTQPCYP7ZAHR3JTATOND5CGS7ENRAGGQSVN33UOQN42EFQQO",
"GBIBV7VU4KNE6PQS5M3JG5VGOREL7JXILTTWWYIXC62GKUSXLY4IGGKE"
"GBTUEWD3WT2IEFDQKPEG6WOAOCJO433IQ3NGHOD6E234QNAD3ZOQ3A7Z"


]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Free Weed Calculator"
ORG_DBA=""
ORG_URL="http://freeweedcalculator.com/"
ORG_LOGO="http://freeweedcalculator.com/TOKELOGO.PNG"
ORG_DESCRIPTION="Free Weed Calculator is a web host of a free calculator. It engages in other related technologies as well."
ORG_PHYSICAL_ADDRESS="Chicago IL"
ORG_PHYSICAL_ADDRESS_ATTESTATION=""
ORG_PHONE_NUMBER="1 (234) 562-2133"
ORG_PHONE_NUMBER_ATTESTATION=""
ORG_KEYBASE="davewinnyk"
ORG_TWITTER="fakedavewinnyk"
ORG_GITHUB="davewinnyk"
ORG_OFFICIAL_EMAIL="davewinnyk@gmail.com"

[[PRINCIPALS]]
name="David Bryan Winnyk"
email="davewinnyk@gmail.com"
keybase="davewinnyk"
twitter="fakedavewinnyk"
github="davewinnyk"
id_photo_hash=""
verification_photo_hash=""


# asset with meta info
[[CURRENCIES]]
code="TOKE"
issuer="GAASD6MEPCGI6J7HUZR7PKYN3V54P7ODIHDNRNCDQURCRDBTZ5AQYIJP"
is_asset_anchored=true
asset_anchor="other"
display_decimals=2
name="The Toke Token"
desc="Buy TOKEs to trade with your buds for smoke sessions. 1 TOKE = 1 SMOKE. The recipient sets the terms of the smoke session and provides the smokable herbs for the session. Stage 1 rollout will attempt to get TOKE to reach the value of an average smoke session. TOKE is all about trust, so please be kind and don't be a jerk! Sellers, buyers, and recipients MUST adhere to the redemption_instructions and conditions listed here."
redemption_instructions="TOKE is anchored to a verbally communicated non-enforcable micro commodity future in the price of smokable herbs on a consumer to consumer level: a smoke session. This asset represents a smart contract where one (1) on-network asset, TOKE, can be traded for one (1) off-network asset, a smoke session, as defined by the recipient or buyer of the token. If the recipient denies a smoke session, the TOKE may also be traded for any other asset on or off the Stellar Network. TOKE should only be used to trade off-network assets acquired within accordance with Federal, State, and Local Laws." 
conditions="By trading in TOKE you agree to our conditions and redemption_instructions.Trading a TOKE does not guarentee the seller a smoke session as the recipient or buyer is ALWAYS in charge of the smoke session, so be sure you trust your recipient. Recipients and Buyers of TOKE should only accept offers if they plan to exchange fairly: for a smoke session or other comparable asset.  Once purchased, it can be traded with anyone for a smoke session. Be cool and don't be a jerk! TOKE, FreeWeedCalculator.com, and listed Principal bare NO responsibility and/or NO guarentee of any transaction or contract made with TOKE. TOKE buyers, sellers, and recipients accept full liability for assets traded and contracts reached."
image="http://freeweedcalculator.com/TOKELOGO.PNG"


